language: php

php:
    - 7.4

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/phpstan analyze
    - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $HOME/.composer/cache/files
